Accessing/Changing specific elements, rows, columns etc.

In [47]:
import numpy as np 

In [48]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [49]:
# get a specific element [r, c]
a[1, 5]
a[1, -2]

13

In [50]:
# get a specific row [r, :]
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
# get a specific column [:, c]
a[:, 1]

array([2, 9])

In [52]:
# [startindex: endindex: stepsize]
a[0,1:-1:2] 

array([2, 4, 6])

In [53]:
a[1, 5] = 30
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 30, 14]])

In [54]:
a[:, 2] = 3
a[:, 3] = [1, 2]
a

array([[ 1,  2,  3,  1,  5,  6,  7],
       [ 8,  9,  3,  2, 12, 30, 14]])

3d example

In [55]:
b = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [56]:
b[0,1,1]
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [57]:
# replace
b[:, 0, :] = [[9,9], [8,8]]
b

array([[[9, 9],
        [3, 4]],

       [[8, 8],
        [7, 8]]])