Initializing Different Types of Array

In [145]:
import numpy as np 

In [146]:
# All 0s matrix
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [147]:
# All 1s matrix
np.ones((3, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [148]:
# Any other number
np.full((2, 3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [149]:
np.full_like(a, 3)

array([[3., 3., 3.],
       [3., 3., 3.]])

In [150]:
# random decimal numbers
np.random.rand(4, 3)

array([[0.68111528, 0.05659514, 0.0914769 ],
       [0.93398879, 0.61091313, 0.49456031],
       [0.2345716 , 0.62186618, 0.7194445 ],
       [0.01745165, 0.71656642, 0.90256287]])

In [151]:
np.random.random_sample(a.shape)

array([[0.96829793, 0.37720502, 0.2360871 ],
       [0.16959229, 0.71163028, 0.12821276]])

In [152]:
# Random integer values
np.random.randint(-3, 7, size=(3, 3))

array([[ 1,  1,  2],
       [-3,  4, -3],
       [ 0, -2,  4]])

In [153]:
# The Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [154]:
# repeat an array
arr = np.array([1, 2, 3])
r = np.repeat(arr, 3)
r

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [155]:
arr = np.array([[1, 2, 3]])
r = np.repeat(arr, 3, axis = 0)
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [156]:
output = np.ones((5, 5))

z = np.zeros((3, 3))
z[1,1] = 9
z
output[1:4 , 1:-1] = z
output


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Be Careful when Copying Arrays

In [157]:
a = np.array([1, 2, 3])
b = a
b[0] = 0
print(b)
print(a)
# both are pointing to same thing

[0 2 3]
[0 2 3]


In [158]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 0
print(b)
print(a)

[0 2 3]
[1 2 3]
