Mathematics

In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3,4])

In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [7]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [9]:
a ** 2 # square

array([ 1,  4,  9, 16], dtype=int32)

In [14]:
# Take the sin/cosine
c = np.array([0,30,45,60,90])
print(np.sin(c))
print(np.cos(c))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]


Linear Algebra

In [16]:
# matrix multiplication
a = np.ones((2, 3))
print(a)
b = np.full((3, 2), 2)
print(b)


np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [17]:
# determinant of a matrix
c = np.identity(3)

np.linalg.det(c)

1.0

Statistics

In [18]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# min
np.min(stats, axis=1)

array([1, 4])

In [20]:
# max
np.max(stats, axis = 0)

array([4, 5, 6])

In [21]:
# sum
np.sum(stats)

21