Miscellaneous

In [39]:
import numpy as np 

Load Data from File

In [40]:
filedata = np.genfromtxt('data.txt', delimiter=',')

In [41]:
# convert to int
filedata = filedata.astype('int32')
filedata

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

Boolean Masking and Advanced Indexing

In [42]:
filedata > 5

array([[False, False, False, False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [43]:
filedata[filedata > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [44]:
# Indexing with a list
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[0, 2, -3]]

array([1, 3, 7])

In [45]:
np.any(filedata > 10, axis=0)

array([False,  True,  True,  True,  True,  True,  True,  True,  True])

In [46]:
np.all(filedata > 7, axis=1)

array([False,  True])

In [47]:
(filedata > 3) & (filedata < 8)

array([[False, False, False,  True,  True,  True,  True, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [48]:
# reverse
~(filedata > 3) & (filedata < 8)

array([[ True,  True,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [79]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]])
print(a[2:-1, 0:2])
print(a[[0, 1, 2, 3], [1, 2, 3, 4]])
print(a[[0,4,5], 3:])
print(a[[0,2,5], 0:2])

[[11 12]
 [16 17]
 [21 22]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
[[ 1  2]
 [11 12]
 [26 27]]
